version: '3.8'
services:
  db:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432